name: FlowerCore
version: '${project.version}'
main: me.emmiesa.flowercore.FlowerCore
authors: ["Emmiesa", "Remi"]
description: '${project.description}'
website: https://dsg.gg/emmiesa
softdepend:
  - PlaceholderAPI
loadbefore:
  - Aspirin
  - AquaCore
  - Basic
  - Clubs
  - Core
  - cCore
  - eCore
  - FlowerHub
  - iCore
  - mCore
  - nCore
  - Phoenix
  - pxCore
  - Synth
  - SharkCore
  - Volcano
  - Voltic
  - xCore
  - zoom
  - zoot