name: FlowerCore
version: '${project.version}'
main: me.emmy.core.FlowerCore
authors: ["Emmy", "Remi"]
description: '${project.description}'
website: https://dsg.gg/dulcy
softdepend:
  - PlaceholderAPI