name: FlowerCore
version: '${project.version}'
main: me.emmiesa.flowercore.FlowerCore
authors: ["Emmy", "Remi"]
description: '${project.description}'
website: https://dsg.gg/dulcy
softdepend:
  - PlaceholderAPI