#
#
#               FlowerCore made by Emmiesa | Settings.yml
#
#
server-name: eu-hub-1
server-region: EU
chat: # Available placeholders %prefix%, %player%, %message%, %suffix%
  format: "%prefix%%player%&7: &f%message%"
grant-settings:
  broadcast: #If somebody is being granted a rank, alert the entire server.
    enabled: true
    message:
      - " "
      - "&7[&cGRANT&7] &a%granted-player%'s rank has been set to %rank% &aby %granted-by%&a."
      - " "
rank-settings:
  list:
    send-as-message: false
    open-menu: true
on-join:
  teleport:
    enabled: true
    location:
      world: world
      x: 0.5
      y: 70.0
      z: 0.5
      yaw: 90.0
      pitch: 0.0
  clear-inventory: false
  set-gamemode:
    enabled: false
    gamemode: "SURVIVAL" #You can use SURVIVAL, CREATIVE, ADVENTURE or SPECTATOR.
vanilla-commands-blocker:
  perm-to-bypass: flower.bypass.cmd.disabler
  disable_me-say: true #Disable /me... & /say...
announce:
  enabled: true
  disabled: "&fNot enabled."
  bungee: true
  cooldown: 15
  command: "play eu-hub-1"
  hover: "&aClick to join!"
  announced-message: "&aYou've announced the game!"
  format: '&b&l%server_name% &7» &b%player_display_name% &fwants you to play! &a(Join)'
socials:
  discord: discord.emmiesa.dev
  website: www.emmiesa.dev
  store: store.emmiesa.dev
  teamspeak: ts.emmiesa.dev
  tiktok: tiktok.com/emmiesadev
  twitter: twitter.com/emmiesadev
  youtube: youtube.com/emmiesadev