#
#
#               FlowerCore made by Emmiesa | Settings.yml
#
#
server-name: eu-hub-1
server-region: EU
chat: # Available placeholders %prefix%, %player%, %message%, %suffix%
  format: "%prefix%%player%%suffix%§7: §f%message%"
grant-settings:
  broadcast: #If somebody is being granted a rank, alert the entire server.
    enabled: true
    message:
      - " "
      - "&b%granted-player%'s rank has been set to %rank% &bby %granted-by%&a."
      - " "
rank-settings:
  list:
    send-as-message: false
    open-menu: true
on-join:
  play-sound:
    enabled: true
    sound: LEVEL_UP
  clear-chat:
    enabled: false
    #This text should always be empty (" "), but let's make it customizable :)
    text: " "
    lines: 500
  teleport:
    enabled: true
    location:
      world: world
      x: 0.5
      y: 73.0
      z: 0.5
      yaw: 90.0
      pitch: 0.0
  clear-inventory: false
  set-gamemode:
    enabled: false
    gamemode: "SURVIVAL" #You can use SURVIVAL, CREATIVE, ADVENTURE or SPECTATOR.
vanilla-commands-blocker:
  perm-to-bypass: flower.bypass.cmd.disabler
  disable_me-say: true #Disable /me... & /say...
announce:
  enabled: true
  disabled: "&fNot enabled."
  bungee: true
  cooldown: 15
  command: "play eu-hub-1"
  hover: "&aClick to join!"
  announced-message: "&aYou've announced the game!"
  format: '&b&l%server_name% &7» &b%prefix%%player_name% &fwants you to play! &a(Join)'
socials:
  discord: discord.flower.club
  website: www.flower.club
  store: store.flower.club
  teamspeak: ts.flower.club
  tiktok: tiktok.com/flowerclub
  twitter: twitter.com/flowerclub
  youtube: youtube.com/flowerclub
announcements:
  enabled: true
  console-enabled: false #Decides if the announcements should be sent to the console aswell.
  send-every: 120
  bars-format: "&7&m------------------------------"
  announcements:
    # Available Placeholders:
    # - %discord%, %twitter%, %tiktok%, %youtube%, %teamspeak%, %store%, %website% - taken from "socials" strings above!
    # - %bars% - taken from the "bars-format" string!
    # - %flowerbar% - A preset bar format (not customizable)!
    message-1:
      - " "
      #- "%bars%"
      - "&b&lAnnouncement:"
      - " &fJoin our discord to get informed about news & updates!"
      - "  &7► &b%discord%"
      #- "%bars%"
      - " "
    message-2:
      - " "
      #- "%bars%"
      - "&b&lAnnouncement:"
      - " &fWatch us on YouTube to have some fun!"
      - "  &7► &b%youtube%"
      #- "%bars%"
      - " "
    message-3:
      - " "
      #- "%bars%"
      - "&b&lAnnouncement:"
      - " &fBuy ranks and more to get more feature access!"
      - "  &7► &b%store%"
      #- "%bars%"
      - " "
    message-4:
      - " "
      #- "%bars%"
      - "&b&lAnnouncement:"
      - " &fVisit our website to check out the latest new!"
      - "  &7► &b%website%"
      #- "%bars%"
      - " "
    message-5:
      - " "
      #- "%bars%"
      - "&b&lAnnouncement:"
      - " &fWatch our TikTok shorts!"
      - "  &7► &b%tiktok%"
      #- "%bars%"
      - " "