name: FlowerCore
version: '1.0-SNAPSHOT'
main: me.emmiesa.flowercore.FlowerCore
authors: ["Emmy", "Remi"]
description: 'A custom server core'
website: https://dsg.gg/emmiesa
softdepend:
  - PlaceholderAPI