name: FlowerCore
version: '1.3.7-DEV'
main: me.emmiesa.flowercore.FlowerCore
authors: ["Emmiesa", "Remi"]
description: 'A custom server core'
website: https://dsg.gg/emmiesa
softdepend:
  - PlaceholderAPI
loadbefore:
  - Aspirin
  - AquaCore
  - Basic
  - Clubs
  - Core
  - cCore
  - eCore
  - FlowerHub
  - iCore
  - mCore
  - nCore
  - Phoenix
  - pxCore
  - Synth
  - SharkCore
  - Volcano
  - Voltic
  - xCore
  - zoom
  - zoot