#
#
#               FlowerCore made by Emmiesa | Settings.yml
#
#
server-name: eu-hub-1
server-region: EU
chat: # Available placeholders %prefix%, %player%, %message%, %suffix%
  format: "%prefix%%player%%suffix%§7: §f%message%"
announcements:
  # Available Placeholders:
  # - %discord%, %twitter%, %tiktok%, %youtube%, %teamspeak%, %store%, %website%,
  # - %bars% - taken from the "bars-format" string
  # - %flowerbar% - A preset bar format (not customizable)
  enabled: true
  send-every: 20
  bars-format: "&7&m------------------------------"
  announcements:
    message-1:
      - " "
      - "%bars%"
      - " &fJoin our discord:"
      - "  &b%discord%"
      - "%bars%"
      - " "
    message-2:
      - " "
      - "%bars%"
      - " &fWatch us on YouTube:"
      - "  &b%youtube%"
      - "%bars%"
      - " "
    message-3:
      - " "
      - "%bars%"
      - " &fBuy ranks and more at:"
      - "  &b%store%"
      - "%bars%"
      - " "
    message-4:
      - " "
      - "%bars%"
      - " &fVisit our website:"
      - "  &b%website%"
      - "%bars%"
      - " "
    message-5:
      - " "
      - "%bars%"
      - " &fWatch our TikTok shorts:"
      - "  &b%tiktok%"
      - "%bars%"
      - " "
grant-settings:
  broadcast: #If somebody is being granted a rank, alert the entire server.
    enabled: true
    message:
      - " "
      - "&b%granted-player%'s rank has been set to %rank% &bby %granted-by%&a."
      - " "
rank-settings:
  list:
    send-as-message: false
    open-menu: true
on-join:
  clear-chat:
    enabled: false
    #This text should always be empty (" "), but let's make it customizable :)
    text: " "
    lines: 500
  teleport:
    enabled: true
    location:
      world: world
      x: 0.5
      y: 70.0
      z: 0.5
      yaw: 90.0
      pitch: 0.0
  clear-inventory: false
  set-gamemode:
    enabled: false
    gamemode: "SURVIVAL" #You can use SURVIVAL, CREATIVE, ADVENTURE or SPECTATOR.
vanilla-commands-blocker:
  perm-to-bypass: flower.bypass.cmd.disabler
  disable_me-say: true #Disable /me... & /say...
announce:
  enabled: true
  disabled: "&fNot enabled."
  bungee: true
  cooldown: 15
  command: "play eu-hub-1"
  hover: "&aClick to join!"
  announced-message: "&aYou've announced the game!"
  format: '&b&l%server_name% &7» &b%prefix%%player_name% &fwants you to play! &a(Join)'
socials:
  discord: discord.emmiesa.dev
  website: www.emmiesa.dev
  store: store.emmiesa.dev
  teamspeak: ts.emmiesa.dev
  tiktok: tiktok.com/emmiesadev
  twitter: twitter.com/emmiesadev
  youtube: youtube.com/emmiesadev