menus:
  settings:
    title: "Settings"
    size: 27
    refill-glass:
      item-title: "&r "
      enabled: true
      data: 15
      slots:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        #- "10"
        #- "11"
        #- "12"
        #- "13"
        #- "14"
        #- "15"
        #- "16"
        #- "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
    settings:
      tgc:
        slot: 10
        material: COMPASS
        data: 0
        name: "&b&lToggle Global chat"
        lore:
          - "&8&m---------------"
          - "&f&oSee the chat or not."
          - " "
          - "&fStatus: &b%status%"
          - " "
          - "&bClick to change!"
          - "&8&m---------------"
        command: "tgc"
      tpv:
        slot: 11
        material: REDSTONE
        data: 0
        name: "&b&lToggle Player Visibility"
        lore:
          - "&8&m---------------"
          - "&f&oSee the players or not."
          - " "
          - "&fStatus: &b%status%"
          - " "
          - "&bClick to change!"
          - "&8&m---------------"
        command: "tpv"
      tpm:
        slot: 12
        material: REDSTONE
        data: 0
        name: "&b&lToggle Private Messages"
        lore:
          - "&8&m---------------"
          - "&f&oSee private messages"
          - "&f&oor not."
          - " "
          - "&fStatus: &b%status%"
          - " "
          - "&bClick to change!"
          - "&8&m---------------"
        command: "tgc"