#
#
#               FlowerCore made by Emmiesa | Settings.yml
#
#
server-name: eu-hub-1
server-region: Europe

chat: # Available placeholders %prefix%, %player%, %message%, %suffix%
  format: "{prefix}{player}{suffix}§r{tag}§7: §f{message}"

#nametags:
#  enabled: true

grant-settings:
  broadcast: #If somebody is being granted a rank, alert the entire server.
    enabled: false
    message:
      - " "
      - "&b%granted-player%'s rank has been set to %rank% &bby %granted-by%&a."
      - " "

rank-settings:
  list:
    send-as-message: true
    open-menu: false

bungee-servers: #Must equal actual bungee servers because this is the completer of admins for the join command.
  - eu-hub-1
  - eu-hub-2
  - eu-sg-1
  - eu-psg-1
  - eu-ug-1
  - eu-um-1
  - eu-sw-1
  - eu-soup
  - eu-practice

default-permissions: #Experimental, better not use it.
  - "none"

on-join:
  play-sound:
    enabled: true
    sound: LEVEL_UP
  clear-chat:
    enabled: false
    text: " "
    lines: 500
  teleport:
    enabled: true
    location:
      world: world
      x: 0.5
      y: 73.0
      z: 0.5
      yaw: 90.0
      pitch: 0.0
  clear-inventory: false
  set-gamemode:
    enabled: false
    gamemode: "SURVIVAL" #You can use SURVIVAL, CREATIVE, ADVENTURE or SPECTATOR.

announce:
  enabled: true
  disabled: "&fNot enabled."
  bungee: true
  cooldown: 15
  command: "play eu-hub-1"
  hover: "&aClick to join eu-hub-1!\n&r \n&c&lWarning: &r&cThis will switch your server!"
  announced-message: "&aYou've announced the game!"
  format: '&b&l%server_name% &7» &b%player-display-name%%player_name% &fwants you to play! &a(Join)' #Placeholders: %player-display-name%, %prefix%, %player_name%, %server_name%

socials:
  discord: discord.flower.club
  website: www.flower.club
  store: store.flower.club
  teamspeak: ts.flower.club
  tiktok: tiktok.com/flowerclub
  twitter: twitter.com/flowerclub
  youtube: youtube.com/flowerclub

punishments:
  default-reason:
    blacklist: "no reason"
    ban: "no reason"
    kick: "absolutely no reason"

sudo:
  exclude-op: false #This prevents OP players to be sudo-ed.

listeners:
  disable-rain: false

placeholders:
  flower_is_staff:
    true: "&aTrue"
    false: "&cFalse"